name: Data Drift Monitoring

on:
  schedule:
    - cron: '0 0 1 * *'  # Run at midnight on the first day of every month

jobs:
  check-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r pyproject.toml --all-extras

      - name: Check Data Drift
        id: drift_check
        run: |
          uv run python -m src.data.collect_data
          uv run python -m src.monitoring.check_drift
          DRIFT_STATUS=$(cat saved_model/metrics/drift_status.txt)
          echo "drift_detected=$DRIFT_STATUS" >> "$GITHUB_OUTPUT"
        
      - name: Retrain if Drift Detected
        if: steps.drift_check.outputs.drift_detected == 'true'
        run: |
          uv run python -m src.data.collect_data
          uv run python -m src.data.preprocess_data
          uv run python -m src.modelling.train
          uv run python -m src.modelling.test

      - name: Deploy New Model
        if: steps.drift_check.outputs.drift_detected == 'true'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-simple-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-simple-app:latest
          kubectl apply -f k8s/deployment.yaml -n mlops-staging
