name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r pyproject.toml --all-extras

      - name: Run Full Pipeline
        run: |
          uv run python -m src.data.collect_data
          uv run python -m src.data.preprocess_data
          uv run python -m src.modelling.train
          uv run python -m src.modelling.test

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Training Report" > report.md
          echo "This is a report on the model training pipeline" >> report.md
          cat saved_model/metrics/overall_metrics.json >> report.md
          cat saved_model/metrics/classification_report.txt >> report.md
          echo '![](saved_model/metrics/confusion_matrix.png "Confusion Matrix")' >> report.md
          cml comment create report.md

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-simple-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-simple-app:latest

      # Currently, the deployment is done manually since the Kubernetes cluster is not available
