name: Model Training and Evaluation

on:
  push:
    branches:
      - 'dev/*'

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r pyproject.toml --all-extras

      - name: Run Training Pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run python -m src.data.collect_data
          uv run python -m src.data.preprocess_data
          uv run python -m src.modelling.train
          uv run python -m src.modelling.test

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Training Report" > report.md
          echo "This is a report on the model training pipeline" >> report.md
          cat saved_model/metrics/overall_metrics.json >> report.md
          echo '![](saved_model/metrics/confusion_matrix.png "Confusion Matrix")' >> report.md
          cat saved_model/metrics/classification_report.txt >> report.md
          cml comment create report.md
