name: Model Training and Evaluation

on:
  push:
    branches:
      - 'dev/*'

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v2
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r pyproject.toml --all-extras

      - name: Run Training Pipeline
        id: pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run python -m src.data.collect_data
          uv run python -m src.data.preprocess_data
          uv run python -m src.modelling.train
          uv run python -m src.modelling.test

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create report header
          echo "## Debug Information" > report.md
          echo "Current working directory:" >> report.md
          echo "\`\`\`" >> report.md
          pwd >> report.md
          echo "\`\`\`" >> report.md

          echo "## Model Training Report" > report.md
          echo "This is a report on the model training pipeline" >> report.md
          echo "<br>" >> report.md
          
          # Add metrics JSON
          echo "\`\`\`json" >> report.md
          cat saved_model/metrics/overall_metrics.json >> report.md
          echo "\`\`\`" >> report.md
          echo "<br>" >> report.md
          
          # Add confusion matrix
          echo '![](saved_model/metrics/confusion_matrix.png "Confusion Matrix")' >> report.md
          echo "<br>" >> report.md
          
          # Add classification report
          echo "```" >> report.md
          cat saved_model/metrics/classification_report.txt >> report.md
          echo "```" >> report.md
          
          # Create CML report
          cml comment create report.md
